### ISSUE TITLE
itemTextField does not display value when property isn't all lowercase

### ISSUE THREAD

**Issue by aiherrera** [eakoriakin/ionic-selectable#188]
if my property were itemTextField="nocuenta" it will work...

`<ion-item>
    <ion-label>Cuenta:</ion-label>
              <ionic-selectable formControlName="cuenta" [items]="cuentas" itemValueField="id" itemTextField="noCuenta"
                [canSearch]="true" (onChange)="selectedCuenta($event)">
              </ionic-selectable>
            </ion-item>`

**Comment by eakoriakin** [comment]
Each item should have a unique ID. Case doesn’t play any role here, it can lowercase or uppercase or a mix of both.

Check that each item has “id” property that you pass to itemValueField.

I’m closing it since it doesn’t seem to be an issue with the component itself.

Feel free to make more comments here in case your issue don’t resolved.
