### ISSUE TITLE
Add "Select all" button when isMultiple is true

### ISSUE THREAD

**Issue by edy-ap** [eakoriakin/ionic-selectable#230]
Its is a feature

**Comment by eakoriakin** [comment]
Hi Edy, this functionality was already implemented in #110 issue.

The thing is that we never know what custom buttons users might need in the footer, and instead of implementing a boolean flag for each custom button, I made the footer customizable.

Here is a [demo](https://stackblitz.com/edit/ionic-selectable-footer-template?file=app/pages/home/home.html), have a look.

**Comment by edy-ap** [comment]
Hi evgenii

I had not seen the issue, thanks for the clarification, I proceed to close it.
