### ISSUE TITLE
onSelect - ionic3 issue

### ISSUE THREAD

**Issue by lmtz07** [eakoriakin/ionic-selectable#248]
onSelect method at the ionic 3 component, is working as onChange method

**Comment by eakoriakin** [comment]
Here's how it works:
1. When `hasConfirmButton` or `isMultiple` is false then both `onSelect` and `onChange` fire when item is selected, because selection and change happen at the same time.
2. When `hasConfirmButton` or `isMultiple` is true then `onSelect` fires when items is selected, but `onChange` fires only when confirmation button is clicked.
